#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcanberra
Version  : 0.30
Release  : 1
URL      : http://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz
Source0  : http://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz
Summary  : Event Sound API
Group    : Development/Tools
License  : LGPL-2.1
Requires: libcanberra-bin
Requires: libcanberra-config
Requires: libcanberra-lib
Requires: libcanberra-doc
Requires: libcanberra-data
BuildRequires : docbook-xml
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(vorbisfile)

%description
libcanberra 0.30
(dot) de>
* [1]License
* [2]News
* [3]Overview
* [4]Current Status
* [5]Documentation
* [6]Requirements
* [7]Installation
* [8]Acknowledgements
* [9]Download

%package bin
Summary: bin components for the libcanberra package.
Group: Binaries
Requires: libcanberra-data
Requires: libcanberra-config

%description bin
bin components for the libcanberra package.


%package config
Summary: config components for the libcanberra package.
Group: Default

%description config
config components for the libcanberra package.


%package data
Summary: data components for the libcanberra package.
Group: Data

%description data
data components for the libcanberra package.


%package dev
Summary: dev components for the libcanberra package.
Group: Development
Requires: libcanberra-lib
Requires: libcanberra-bin
Requires: libcanberra-data
Provides: libcanberra-devel

%description dev
dev components for the libcanberra package.


%package doc
Summary: doc components for the libcanberra package.
Group: Documentation

%description doc
doc components for the libcanberra package.


%package lib
Summary: lib components for the libcanberra package.
Group: Libraries
Requires: libcanberra-data
Requires: libcanberra-config

%description lib
lib components for the libcanberra package.


%prep
%setup -q -n libcanberra-0.30

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-settings-daemon-3.0/gtk-modules/canberra-gtk-module.desktop

%files bin
%defattr(-,root,root,-)
/usr/bin/canberra-boot
/usr/bin/canberra-gtk-play

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/canberra-system-bootup.service
/usr/lib/systemd/system/canberra-system-shutdown-reboot.service
/usr/lib/systemd/system/canberra-system-shutdown.service

%files data
%defattr(-,root,root,-)
/usr/share/gdm/autostart/LoginWindow/libcanberra-ready-sound.desktop
/usr/share/gnome/autostart/libcanberra-login-sound.desktop
/usr/share/gnome/shutdown/libcanberra-logout-sound.sh
/usr/share/vala/vapi/libcanberra-gtk.vapi
/usr/share/vala/vapi/libcanberra.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libcanberra/*
/usr/share/gtk-doc/html/libcanberra/ch01.html
/usr/share/gtk-doc/html/libcanberra/home.png
/usr/share/gtk-doc/html/libcanberra/index.html
/usr/share/gtk-doc/html/libcanberra/index.sgml
/usr/share/gtk-doc/html/libcanberra/left.png
/usr/share/gtk-doc/html/libcanberra/libcanberra-canberra-gtk.html
/usr/share/gtk-doc/html/libcanberra/libcanberra-canberra.html
/usr/share/gtk-doc/html/libcanberra/libcanberra.devhelp2
/usr/share/gtk-doc/html/libcanberra/right.png
/usr/share/gtk-doc/html/libcanberra/style.css
/usr/share/gtk-doc/html/libcanberra/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
/usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk3-module.so
/usr/lib64/libcanberra-0.30/libcanberra-alsa.so
/usr/lib64/libcanberra-0.30/libcanberra-gstreamer.so
/usr/lib64/libcanberra-0.30/libcanberra-multi.so
/usr/lib64/libcanberra-0.30/libcanberra-null.so
/usr/lib64/libcanberra-0.30/libcanberra-oss.so
/usr/lib64/libcanberra-0.30/libcanberra-pulse.so
