#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libcanberra
Version  : 0.30
Release  : 19
URL      : http://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz
Source0  : http://0pointer.de/lennart/projects/libcanberra/libcanberra-0.30.tar.xz
Summary  : Event Sound API
Group    : Development/Tools
License  : LGPL-2.1
Requires: libcanberra-bin = %{version}-%{release}
Requires: libcanberra-data = %{version}-%{release}
Requires: libcanberra-lib = %{version}-%{release}
BuildRequires : docbook-xml
BuildRequires : fribidi-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libtool-dev
BuildRequires : libxslt-bin
BuildRequires : pkg-config
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(atk)
BuildRequires : pkgconfig(gdk-2.0)
BuildRequires : pkgconfig(gdk-3.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gstreamer-1.0)
BuildRequires : pkgconfig(gthread-2.0)
BuildRequires : pkgconfig(gtk+-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(vorbisfile)
BuildRequires : pkgconfig(x11)

%description
libcanberra 0.30
(dot) de>
* [1]License
* [2]News
* [3]Overview
* [4]Current Status
* [5]Documentation
* [6]Requirements
* [7]Installation
* [8]Acknowledgements
* [9]Download

%package bin
Summary: bin components for the libcanberra package.
Group: Binaries
Requires: libcanberra-data = %{version}-%{release}

%description bin
bin components for the libcanberra package.


%package data
Summary: data components for the libcanberra package.
Group: Data

%description data
data components for the libcanberra package.


%package dev
Summary: dev components for the libcanberra package.
Group: Development
Requires: libcanberra-lib = %{version}-%{release}
Requires: libcanberra-bin = %{version}-%{release}
Requires: libcanberra-data = %{version}-%{release}
Provides: libcanberra-devel = %{version}-%{release}
Requires: libcanberra = %{version}-%{release}

%description dev
dev components for the libcanberra package.


%package doc
Summary: doc components for the libcanberra package.
Group: Documentation

%description doc
doc components for the libcanberra package.


%package lib
Summary: lib components for the libcanberra package.
Group: Libraries
Requires: libcanberra-data = %{version}-%{release}

%description lib
lib components for the libcanberra package.


%prep
%setup -q -n libcanberra-0.30
cd %{_builddir}/libcanberra-0.30

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1600302258
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --disable-oss --disable-alsa --disable-gstreamer --disable-tdb
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1600302258
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/gnome-settings-daemon-3.0/gtk-modules/canberra-gtk-module.desktop

%files bin
%defattr(-,root,root,-)
/usr/bin/canberra-gtk-play

%files data
%defattr(-,root,root,-)
/usr/share/gdm/autostart/LoginWindow/libcanberra-ready-sound.desktop
/usr/share/gnome/autostart/libcanberra-login-sound.desktop
/usr/share/gnome/shutdown/libcanberra-logout-sound.sh
/usr/share/vala/vapi/libcanberra-gtk.vapi
/usr/share/vala/vapi/libcanberra.vapi

%files dev
%defattr(-,root,root,-)
/usr/include/canberra-gtk.h
/usr/include/canberra.h
/usr/lib64/libcanberra-gtk.so
/usr/lib64/libcanberra-gtk3.so
/usr/lib64/libcanberra.so
/usr/lib64/pkgconfig/libcanberra-gtk.pc
/usr/lib64/pkgconfig/libcanberra-gtk3.pc
/usr/lib64/pkgconfig/libcanberra.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libcanberra/*
/usr/share/gtk-doc/html/libcanberra/ch01.html
/usr/share/gtk-doc/html/libcanberra/home.png
/usr/share/gtk-doc/html/libcanberra/index.html
/usr/share/gtk-doc/html/libcanberra/index.sgml
/usr/share/gtk-doc/html/libcanberra/left.png
/usr/share/gtk-doc/html/libcanberra/libcanberra-canberra-gtk.html
/usr/share/gtk-doc/html/libcanberra/libcanberra-canberra.html
/usr/share/gtk-doc/html/libcanberra/libcanberra.devhelp2
/usr/share/gtk-doc/html/libcanberra/right.png
/usr/share/gtk-doc/html/libcanberra/style.css
/usr/share/gtk-doc/html/libcanberra/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk3-module.so
/usr/lib64/libcanberra-0.30/libcanberra-multi.so
/usr/lib64/libcanberra-0.30/libcanberra-null.so
/usr/lib64/libcanberra-0.30/libcanberra-pulse.so
/usr/lib64/libcanberra-gtk.so.0
/usr/lib64/libcanberra-gtk.so.0.1.9
/usr/lib64/libcanberra-gtk3.so.0
/usr/lib64/libcanberra-gtk3.so.0.1.9
/usr/lib64/libcanberra.so.0
/usr/lib64/libcanberra.so.0.2.5
